site_name: 艇仔粥


nav:
  - Home: index.md
  - 丨: mis/blankpage.md
  - Tech Talk:
      爬行動物:
        爬取steam游戲榜單: tech/steam-crawling-python.md
        爬取校招網招聘信息: tech/recruitment2021-crawling-python.md
        爬取豆瓣帖子: tech/douban-crawling-python.md 
      突發奇想:
        Mkdocs混合頁面: tech/mixedmkdocs.md
        語音助手與天氣: tech/analytics-weather.md
  - Tap Water:
    - Preface: poems/preface.md
    - Chapter I: 
        再來七杯自來水: poems/ch1/tap-water.md
        Celeste: poems/ch1/celeste.md
        魚腸: poems/ch1/fishsausage.md
    - Chapter IV:
        和歌山之旅: poems/ch4/trip-of-wakayama.md
        奧克蘭的初夏: poems/ch4/trip-of-auckland.md
        Wu Kai Sha: poems/ch4/wukaisha.md 
        成都的四日三夜: poems/ch4/trip-of-chengdu.md
    - Chapter VI:
        音符: poems/ch6/note.md
        宇宙飛船: poems/ch6/spaceship.md
        Untitled: poems/ch6/Untitled.md
    - Chapter VII:
        緊急想念: poems/ch7/urgently-miss.md
        不可抗力: poems/ch7/force-majeure.md
  - mini Ted Talk:
      關於選擇: talk/about-life-choices.md
      向流星許願: talk/grant-wishes.md
      狩月人: talk/moon-hunter.md
      電子湯圓: talk/digital-sweetdumpling.md

  - About: about.md
  - 建站日志: mis/websitelog.md 



theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  font: 
    text: Noto Serif SC
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  
  palette:
    - scheme: default
      primary: blue grey
      
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    



markdown_extensions:
  
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


copyright: Copyright &copy; 2021 TingZaiZuk

extra:
  homepage: https://herointene.github.io

extra_css:
  - stylesheets/extra.css