# Copyright (c) 2021 Ted WU <wulited@outlook.com>

site_name: 艇仔粥 TingZaiZuk
site_url: https://herointene.github.io
site_author: Ted WU
site_description: >-
  Personal website introduced technical skills
  sharing / personal portfolio / articles / music .etc

copyright: Copyright &copy; 2021-2022 TingZaiZuk

nav:
  - Home: index.md
  - 丨: mis/blankpage.md
  - Tech Talk:
      Mkdocs網站搭建:
        快速概覽 & 簡介: tech/mkdocsbuild.md
        用Markdown寫文章: tech/md-guide.md
        Mkdocs混合頁面: tech/mixedmkdocs.md
        導航欄設置心得: tech/mkdocs-nav.md
        Mkdocs漢語字體: tech/chnfonts.md
      爬行動物:
        爬取steam游戲榜單: tech/steam-crawling-python.md
        爬取校招網招聘信息: tech/recruitment2021-crawling-python.md
        爬取豆瓣帖子: tech/douban-crawling-python.md 
      VUE呢: 
        開發心得: tech/vue-tips.md
        循環裏匹配不同樣式: tech/vue-setstyleinloop.md
        組件間的數據傳輸: tech/vue-delivermethods.md
      突發奇想:
        語音助手與天氣: tech/analytics-weather.md
  - Tap Water:
      Preface: poems/preface.md
      Chapter I: 
        再來七杯自來水: poems/ch1/tap-water.md
        Celeste: poems/ch1/celeste.md
        魚腸: poems/ch1/fishsausage.md
        袁鳳嵐: poems/ch1/sierrablue.md
      Chapter IV:
        和歌山之旅: poems/ch4/trip-of-wakayama.md
        奧克蘭的初夏: poems/ch4/trip-of-auckland.md
        Wu Kai Sha: poems/ch4/wukaisha.md 
        成都的四日三夜: poems/ch4/trip-of-chengdu.md
      Chapter VI:
        音符: poems/ch6/note.md
        宇宙飛船: poems/ch6/spaceship.md
        Untitled: poems/ch6/Untitled.md
      Chapter VII:
        緊急想念: poems/ch7/urgently-miss.md
        不可抗力: poems/ch7/force-majeure.md
  - mini Ted Talk:
      關於選擇: talk/about-life-choices.md
      向流星許願: talk/grant-wishes.md
      狩月人: talk/moon-hunter.md
      電子湯圓: talk/digital-sweetdumpling.md
      2021之總結: talk/2021conclusion.md

  - About: about.md



theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo.png
  logo: assets/logo.png

  font: 
    text: Noto Serif SC
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  
  palette:
    - scheme: default
      primary: blue grey
      
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    



markdown_extensions:
  
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables




extra:
  homepage: https://herointene.github.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/herointene
      name: Github
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tedilitarianism/
      name: Instagram

    - icon: fontawesome/solid/paper-plane
      link: mailto:<wulited@outlook.com>
      name: Email me
  analytics:
    provider: google
    property: G-NSSC5W311R
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js