site_name: 艇仔粥


nav:
  - Home: index.md
  - Tech Talk:
      爬行動物:
        爬取steam游戲榜單: tech/steam-crawling-python.md
        爬取校招網招聘信息: tech/recruitment2021-crawling-python.md
        爬取豆瓣帖子: tech/douban-crawling-python.md 
  - Tap Water:
    - Preface: poems/preface.md
    - Chapter I: 
        再來七杯自來水: poems/ch1/tap-water.md
        Celeste: poems/ch1/celeste.md
    - Chapter IV:
        和歌山之旅: poems/ch4/trip-of-wakayama.md
  - mini Ted Talk:
      關於選擇: talk/about-life-choose.md

  - About: about.md
  - 建站日志: mis/websitelog.md 



theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  font: 
    text: Noto Serif SC
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    



markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2021 Ted WU

extra:
  generator: false