site_name: 艇仔粥


nav:
  - Home: index.md
  - 丨: mis/blankpage.md
  - Tech Talk:
      爬行動物:
        爬取steam游戲榜單: tech/steam-crawling-python.md
        爬取校招網招聘信息: tech/recruitment2021-crawling-python.md
        爬取豆瓣帖子: tech/douban-crawling-python.md 
  - Tap Water:
    - Preface: poems/preface.md
    - Chapter I: 
        再來七杯自來水: poems/ch1/tap-water.md
        Celeste: poems/ch1/celeste.md
    - Chapter IV:
        和歌山之旅: poems/ch4/trip-of-wakayama.md
        奧克蘭的初夏: poems/ch4/trip-of-auckland.md
  - mini Ted Talk:
      關於選擇: talk/about-life-choices.md
      向流星許願: talk/grant-wishes.md
      狩月人: talk/moon-hunter.md
      電子湯圓: talk/digital-sweetdumpling.md

  - About: about.md
  - 建站日志: mis/websitelog.md 



theme:
  name: material
  logo: assets/logo.png
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  font: 
    text: Noto Serif SC
  palette:
    - scheme: default
      primary: blue grey
      
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    



markdown_extensions:
  
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2021 Ted WU

extra:
  homepage: https://herointene.github.io

extra_css:
  - stylesheets/extra.css